version: "2.0"

services:
  zookeeper:
    image: debezium/zookeeper:0.3
    container_name: zookeeper
    ports: 
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: debezium/kafka:0.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
  connect: 
    image: debezium/connect:0.3
    container_name: connect
    environment: 
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
    ports: 
      - "8083:8083"
  mysql:
    image: debezium/example-mysql:0.3
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
